# Site settings
title: Test
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mhlr.github.com" # the base hostname & protocol for your site
twitter_username: dmhlr
github_username:  mhlr

# Build settings
markdown: kramdown
