---
title: Test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: ''
baseurl: ''
url: http://mhlr.github.com
twitter_username: dmhlr
github_username: mhlr
markdown: kramdown
